
services: 
    mariadb:
      build: ./requirements/mariadb/
      container_name: mariadb
      restart: always
      env_file: .env
      volumes:
        - mariadb_volume:/var/lib/mysql
      networks:
        - inception
    wordpress:
      build: ./requirements/wordpress/
      container_name: wordpress
      restart : always
      env_file: .env
      volumes:
        - wordpress_volume:/var/www/html
      depends_on :
        - mariadb
      networks:
        - inception
    nginx:
      build: ./requirements/nginx/
      container_name : nginx
      restart: always
      env_file: .env
      volumes:
        - wordpress_volume:/var/www/html
      depends_on :
        - wordpress
      networks :
        - inception
      ports:
        - "443:443"
    
    adminer:
      build: ./requirements/bonusX/adminer/
      container_name: adminer
      restart: always
      env_file: .env
      networks:
        - inception
      ports:
        - "8080:8080"

    redis:
      build: ./requirements/bonusX/redis/ 
      container_name: redis
      restart: always
      env_file: .env
      networks:
        - inception
    
    static_website:
      build: ./requirements/bonusX/static_website/
      container_name: static_website
      restart: always
      env_file: .env
      networks:
        - inception
      ports:
        - "3000:3000"

volumes:
  wordpress_volume:
    name: "wordpress_volume"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zahiri/data/wordpress
  
  mariadb_volume:
    name: "mariadb_volume"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zahiri/data/mariadb
  
networks:
  inception:
    name: "inception"
    driver: bridge
