version: '3.8'

services:
    mariadb:
      build: ./requirements/mariadb/
      container_name: mariadb
      restart: always
      env_file: .env
      volumes:
        - mariadb_volume:/var/lib/mysql
      networks:
        - inception
    wordpress:
      build: ./requirements/wordpress/
      container_name: wordpress
      restart : always
      env_file: .env
      volumes:
        - wordpress_volume:/var/www/html
      depends_on :
        - mariadb
      networks:
        - inception
    nginx:
      build: ./requirements/nginx/
      container_name : nginx
      restart: always
      env_file: .env
      volumes:
        - wordpress_volume:/var/www/html
      depends_on :
        - wordpress
      networks :
        - inception
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zahiri/data/wordpress
  
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zahiri/data/mariadb
  
networks:
  inception:
    driver: bridge